CompileFlags:
  Remove:
    - -fno-tree-switch-conversion
    - -fno-fat-lto-objects
    - -mlongcalls
    - -fstrict-volatile-bitfields

Diagnostics:
  Suppress: [unused-includes] # Ignore unused-includes
